# Service and Deployment configuration for Policy service deployment.
##################################################################################################
# Policy api
##################################################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-api
data:
  #spring.profiles.active: local
  external.services.customer.uri: http://customer-api:8080
  spring.data.mongodb.uri: mongodb+srv://training_rw_user:training_rw_password@training-cluster-dev.z7ar8.mongodb.net/customer-db
  #datastore.mongodb.collection.name: customer-coll-local
---
apiVersion: v1
kind: Service
metadata:
  name: policy-api
  labels:
    app: policy-api
    service: policy-api
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: policy-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-api-release-1.0.0
  labels:
    app: policy-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-api
      version: v1
  template:
    metadata:
      labels:
        app: policy-api
        version: v1
    spec:
      containers:
      - name: policy-api
        image: quay.io/necloudnativetraining/policy-api:release-1.0.0
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: customer-api
        ports:
        - containerPort: 8080
---
