apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: policy-api-virtual-service
spec:
  gateways:
    - acctrainings-vikas-gateway
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /policy
        - uri:
            prefix: /policies
      route:
        - destination:
            host: policy-api
            port:
              number: 8080
